spring:
  application:
    name: platform-server
  data:
    mongodb:
      host: localhost
      database: platform
      username: root
      password: ${platform_db_pass}
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}

logging:
  level:
    org.springframework.security: TRACE

